config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
resources :qqconnects, only: [:create, :update, :destroy]

get 'qqlogincode' =>  'qqlogins#new'
delete 'qqlogout' =>  'qqlogins#destroy'
get 'mmlogincode' =>  'mmlogins#new'
delete 'mmlogout' =>  'mmlogins#destroy'

app/views/my/account.html.erb
<div class="contextual">
<%= additional_emails_link(@user) %>
<%= link_to(l(:button_change_password), {:action => 'password'}, :class => 'icon icon-passwd') if @user.change_password_allowed? %>
<%= call_hook(:view_my_account_contextual, :user => @user)%>
</div>

<h2>
  <%= avatar_edit_link(@user, :size => "50") %>
  <%=l(:label_my_account)%>
</h2>

<%= error_messages_for 'user' %>

<%= labelled_form_for :user, @user,
                     :url => { :action => "account" },
                     :html => { :id => 'my_account_form',
                                :method => :post } do |f| %>
<div class="splitcontentleft">
<fieldset class="box tabular">
  <legend><%=l(:label_information_plural)%></legend>
  <p><%= f.text_field :firstname, :required => true %></p>
  <p><%= f.text_field :lastname, :required => true %></p>
  <p><%= f.text_field :mail, :required => true %></p>
  <% unless @user.force_default_language? %>
  <p><%= f.select :language, lang_options_for_select %></p>
  <% end %>
  <% if Setting.openid? %>
  <p><%= f.text_field :identity_url  %></p>
  <% end %>

  <% @user.custom_field_values.select(&:editable?).each do |value| %>
    <p><%= custom_field_tag_with_label :user, value %></p>
  <% end %>
  <%= call_hook(:view_my_account, :user => @user, :form => f) %>
</fieldset>

<!using :plugin to locate the image directory-->
<p align="center">
  <% if !qq_binded? && !mm_logged_in? %>
    <%= link_to image_tag("bt_blue_24X24.png", alt: l(:connectlogo), :plugin => "qqs", :title => l(:label_qq_bind)), qqconnects_path +  "?from=qq", method: :post %>
  <% end %>
  <% if qq_binded? && !mm_logged_in? %>
    <%= link_to image_tag("bt_blue_24X24.png", alt: l(:connectlogo), :plugin => "qqs", :title => l(:label_qq_bind_update)), qqconnect_path(@qqconnect) + "?from=qq", method: :patch %>
    <%= "{ #{@nickname} } "%>
    <%= link_to image_tag("bind_broken.png", alt: l(:connectlogo), :plugin => "qqs", :title => l(:label_qq_bind_drop)), qqconnect_path(@qqconnect) + "?to=qq", method: :delete, data: { confirm: l(:text_are_you_sure) } %> 
  <% end %>
  <% if qq_binded? && mm_logged_in? %>
    <%= "{ #{@nickname} } "%>
    <%= link_to image_tag("bind_broken.png", alt: l(:connectlogo), :plugin => "qqs", :title => l(:label_qq_bind_drop)), qqconnect_path(@qqconnect) + "?to=qq", method: :delete, data: { confirm: l(:text_are_you_sure) } %> 
  <% end %>
</p>
<p align="center">
  <% if !mm_binded? && mm_logged_in? %>
    <%= link_to image_tag("icon24_appwx_logo.png", alt: l(:mmconnectlogo), :plugin => "qqs", :title => l(:label_mm_bind)), qqconnects_path +  "?from=mm", method: :post %>
  <% end %>
  <% if mm_binded? && mm_logged_in? %>
    <%= link_to image_tag("icon24_appwx_logo.png", alt: l(:mmconnectlogo), :plugin => "qqs", :title => l(:label_mm_bind_update)), qqconnect_path(@qqconnect) + "?from=mm", method: :patch %>
    <%= "{ #{@mm_nickname} } "%>
    <%= link_to image_tag("bind_broken.png", alt: l(:mmconnectlogo), :plugin => "qqs", :title => l(:label_mm_bind_drop)), qqconnect_path(@qqconnect) + "?to=mm", method: :delete, data: { confirm: l(:text_are_you_sure) } %> 
  <% end %>
  <% if mm_binded? && !mm_logged_in? %>
    <%= "{ #{@mm_nickname} } "%>
    <%= link_to image_tag("bind_broken.png", alt: l(:mmconnectlogo), :plugin => "qqs", :title => l(:label_mm_bind_drop)), qqconnect_path(@qqconnect) + "?to=mm", method: :delete, data: { confirm: l(:text_are_you_sure) } %> 
  <% end %>
</p>


<p class="mobile-hide"><%= submit_tag l(:button_save) %></p>
</div>

<div class="splitcontentright">
<fieldset class="box">
  <legend><%=l(:field_mail_notification)%></legend>
  <%= render :partial => 'users/mail_notifications' %>
</fieldset>

<fieldset class="box tabular">
  <legend><%=l(:label_preferences)%></legend>
  <%= render :partial => 'users/preferences' %>
  <%= call_hook(:view_my_account_preferences, :user => @user, :form => f) %>
</fieldset>

<p class="mobile-show"><%= submit_tag l(:button_save) %></p>
</div>
<% end %>

<% content_for :sidebar do %>
<%= render :partial => 'sidebar' %>
<% end %>

<% html_title(l(:label_my_account)) -%>