config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
resources :qqconnects, only: [:create, :update, :destroy]

get 'qqlogincode' =>  'qqlogins#new'
delete 'qqlogout' =>  'qqlogins#destroy'
get 'mmlogincode' =>  'mmlogins#new'
delete 'mmlogout' =>  'mmlogins#destroy'

app/views/layouts/base.html.erb
<!DOCTYPE html>
<html lang="<%= current_language %>">
<head>
<meta charset="utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge"/> 
<title><%= html_title %></title>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<meta name="description" content="<%= Redmine::Info.app_name %>" />
<meta name="keywords" content="issue,bug,tracker" />
<meta property="qc:admins" content="<%= Setting["plugin_qqs"][:qq_validate_code] %>" />
<%= csrf_meta_tag %>
<%= favicon %>
<%= stylesheet_link_tag 'jquery/jquery-ui-1.11.0', 'application', 'responsive', :media => 'all' %>
<%= stylesheet_link_tag 'rtl', :media => 'all' if l(:direction) == 'rtl' %>
<%= javascript_heads %>
<%= heads_for_theme %>
<%= call_hook :view_layouts_base_html_head %>
<!-- page specific tags -->
<%= yield :header_tags -%>
</head>
<body class="<%= body_css_classes %>">
<div id="wrapper">

<div class="flyout-menu js-flyout-menu">


    <% if User.current.logged? || !Setting.login_required? %>
        <div class="flyout-menu__search">
            <%= form_tag({:controller => 'search', :action => 'index', :id => @project}, :method => :get ) do %>
            <%= hidden_field_tag(controller.default_search_scope, 1, :id => nil) if controller.default_search_scope %>
            <%= label_tag 'flyout-search', '&#9906;'.html_safe, :class => 'search-magnifier search-magnifier--flyout' %>
            <%= text_field_tag 'q', @question, :id => 'flyout-search', :class => 'small js-search-input', :placeholder => l(:label_search) %>
            <% end %>
        </div>
    <% end %>

    <% if User.current.logged? %>
        <div class="flyout-menu__avatar <% if !Setting.gravatar_enabled? %>flyout-menu__avatar--no-avatar<% end %>">
            <% if Setting.gravatar_enabled? %>
                <%= link_to(avatar(User.current, :size => "80"), user_path(User.current)) %>
            <% end %>
            <%= link_to_user(User.current, :format => :username) %>
        </div>
    <% end %>

    <% if display_main_menu?(@project) %>
        <h3><%= l(:label_project) %></h3>
        <span class="js-project-menu"></span>
    <% end %>

    <h3><%= l(:label_general) %></h3>
    <span class="js-general-menu"></span>

    <span class="js-sidebar flyout-menu__sidebar"></span>

    <h3><%= l(:label_profile) %></h3>
    <span class="js-profile-menu"></span>

</div>

<div id="wrapper2">
<div id="wrapper3">
<div id="top-menu">
    <div id="account">
        <%= render_menu :account_menu -%>
    </div>
    
    <% if session[:qq_nickname].nil? && session[:mm_nickname].nil? %>
        <%= content_tag('div', link_to(image_tag("bt_blue_24X24.png", alt: l(:connectlogo), :plugin => "qqs", :title => l(:connectwelcome)), qqlogincode_path), :id => 'loggedas')  %>        
        <%= content_tag('div', link_to(image_tag("mm_logo.png", alt: l(:mmconnectlogo), :plugin => "qqs", :title => l(:mmconnectwelcome)), mmlogincode_path), :id => 'loggedas')  %>        
    <% end %>
    <% if !session[:qq_nickname].nil?%>
        <%= content_tag('div', link_to(image_tag(session[:qq_avater_url], :width => 24, :height => 24, :title => "#{l(:label_logout)}#{session[:qq_nickname]}"), qqlogout_path, method: :delete, :data => {:confirm => l(:text_sure_qqlogout)}), :id => 'loggedas')  %>
        <%= content_tag('div', "#{l(:notice_qq_welcome)}#{session[:qq_nickname]}".html_safe, :id => 'loggedas') %>
    <% else %>
        <% if !session[:mm_nickname].nil?%>
        <%= content_tag('div', link_to(image_tag(session[:qq_avater_url], :width => 24, :height => 24, :title => "#{l(:label_logout)}#{session[:mm_nickname]}"), mmlogout_path, method: :delete,  :data => {:confirm => l(:text_sure_qqlogout)}), :id => 'loggedas')  %>
            <%= content_tag('div', "#{l(:notice_mm_welcome)}#{session[:mm_nickname]}".html_safe, :id => 'loggedas') %>
        <% end %>
    <% end %>
        
    <%= content_tag('div', "#{l(:label_logged_as)} #{link_to_user(User.current, :format => :username)}".html_safe, :id => 'loggedas') if User.current.logged? %>
    <%= render_menu :top_menu if User.current.logged? || !Setting.login_required? -%>
</div>

<div id="header">

    <a href="#" class="mobile-toggle-button js-flyout-menu-toggle-button"></a>

    <% if User.current.logged? || !Setting.login_required? %>
    <div id="quick-search">
        <%= form_tag({:controller => 'search', :action => 'index', :id => @project}, :method => :get ) do %>
        <%= hidden_field_tag(controller.default_search_scope, 1, :id => nil) if controller.default_search_scope %>
        <label for='q'>
          <%= link_to l(:label_search), {:controller => 'search', :action => 'index', :id => @project}, :accesskey => accesskey(:search) %>:
        </label>
        <%= text_field_tag 'q', @question, :size => 20, :class => 'small', :accesskey => accesskey(:quick_search) %>
        <% end %>
        <%= render_project_jump_box %>
    </div>
    <% end %>

    <h1><%= page_header_title %></h1>

    <% if display_main_menu?(@project) %>
    <div id="main-menu">
        <%= render_main_menu(@project) %>
    </div>
    <% end %>
</div>

<div id="main" class="<%= sidebar_content? ? '' : 'nosidebar' %>">
    <div id="sidebar">
        <%= yield :sidebar %>
        <%= view_layouts_base_sidebar_hook_response %>
    </div>

    <div id="content">
        <%= render_flash_messages %>
        <%= yield %>
        <%= call_hook :view_layouts_base_content %>
        <div style="clear:both;"></div>
    </div>
</div>
</div>

<div id="ajax-indicator" style="display:none;"><span><%= l(:label_loading) %></span></div>
<div id="ajax-modal" style="display:none;"></div>

<div id="footer">
  <div class="bgl"><div class="bgr">
    Powered by <%= link_to Redmine::Info.app_name, Redmine::Info.url %> &copy; 2006-2016 Jean-Philippe Lang
    <%= debug(params) if Rails.env.development? %>
  </div>
  </div>
</div>
</div>
</div>
<%= call_hook :view_layouts_base_body_bottom %>
</body>
</html>